image: Visual Studio 2019 # образ для сборки

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint && yarn test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://%GITHUB_TOKEN%:x-oauth-basic@github.com" > "%HOMEPATH%\.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose